#!/usr/bin/env python3
"""This is the kospex git CLI helper tool."""
import click
import time
from kospex_core import GitRepo
import kospex_utils as KospexUtils

@click.group()
def cli():
    """kgit (Kospex Git) is a utility for doing git things with kospex use cases.
    
    It is designed to help understand the structure of code, who are developers and
    changes over time.

    For documentation on how commands run `kospex COMMAND --help`.
    
    """

@cli.command("status")
#@click.option('-repo', type=GitRepo(), help="Git repository.")
#@click.argument('repo', type=click.Path(exists=True))
@click.argument('repo',  type=GitRepo())
# pylint: disable=unused-argument
def status(repo):
    """Date and commit metadata for the given repo."""
    print(repo)
    st = time.time()
    stats = KospexUtils.get_git_stats(repo, 30)
    for x in stats.keys():
        print(x + " => ", end="")
        print(stats[x])
    et = time.time()
    elapsed_time = et - st
    print('Execution time:', elapsed_time, 'seconds')

if __name__ == '__main__':
    cli()
