#!/usr/bin/env python3
"""This is the kospex command line tool."""
import os
import os.path
import logging
from datetime import datetime
from shutil import which
import click
from kospex_core import Kospex, GitRepo
import kospex_utils as KospexUtils
from kospex_git import KospexGit
from kospex_query import KospexQuery
import kospex_schema as KospexSchema
from kospex_dependencies import KospexDependencies

KospexUtils.init()
kospex = Kospex()
log = logging.getLogger(__name__)
#logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)

@click.group()
def cli():
    """Kospex is a tool for assessing code and git repositories.
    
    It is designed to help understand the structure of code, who are developers and
    changes over time.

    For documentation on how commands run `kospex COMMAND --help`.

    See also https://kospex.io/
    
    """

@cli.command("init")
@click.option('--default', is_flag=True, default=False, help="Create the default ~/code directory.")
def kospex_init(default):
    """ Perform basic initial setup."""
    kospex_code = os.path.expanduser("~/code")
    kconf = KospexUtils.get_kospex_config()
    installed = which('scc')
    if not installed:
        print("Please install scc from https://github.com/boyter/scc")
        print("This is used to count lines of code, complexity and determine the language.")

    if default:
        if not os.path.exists(kospex_code):
            os.makedirs(kospex_code)
        else:
            print("Directory already exists.")
    else:
        if os.path.exists(kospex_code):
            print("~/code directory exists.")
            print("If you want to overide the code directory")
            print(f"edit the {kconf} file.")
        else:
            print("Directory does not exist.")
            print("Run with --default to create ~/code directory.")
            print(f"or edit the {kconf} file and change the KOSPEX_CODE.")


@cli.command("summary")
@click.option('-out', type=click.STRING,help="filename to write CSV results to.")
@click.option('-server', type=click.STRING, help="Git server to query.")
@click.option('-query_file', type=click.Path(exists=True), help="CSV file to query with.")
@click.option('-query', type=click.STRING, help="Query for CSV file. E.g.  to query with.")
# pylint: disable=unused-argument
def summary(out,server,query_file):
    """ Provide a summary of all the known repositories."""
    params = locals()
    kospex.summary(results_file=out, **params)

@cli.command("sync")
@click.option('--no-scc', is_flag=True, default=False, help="Skip scc analysis.")
@click.argument('repo', type=GitRepo())
def sync(repo,no_scc):
    """Sync a single repo to the kospex DB, using the native git commands."""
    installed = which('scc')
    if not installed:
        print("Please install scc from https://github.com/boyter/scc")
        print("This is used to count lines of code, complexity and determine the language.")
        print("or run sync with --no-scc to skip this step.")
    kospex.sync_repo(repo, no_scc=no_scc)

#@cli.command("sync")
#@click.option('-previous', type=int, help='# Commits to sync from the oldest in kospex DB.')
#@click.argument('repo', type=GitRepo())
#def sync(repo, previous):
#    """Sync a single repo to the kospex DB.
#
#    Available switches:
#
#    -previous to get the previous N commits using the "-before" date
#
#    Future (not implemented yet) switches:
#
#    -before to specify the the commits before a date
#
#    -after to specify the the commits after a date
#
#    -hash to get all the commits after a hash
#
#    -before and -previous to get the previous N commits before a date
#
#    -next to get the next N commits after the "-after" date
#    """
#    params = {}
#   params['previous'] = previous
#    kospex.sync_repo(repo, **params)

@cli.command("sync-directory")
@click.argument('directory', type=click.Path(exists=True))
def sync_directory(directory):
    """Sync all Git repos found in the data directory to the kospex DB."""
    # Find all the repos in the directory
    repos = KospexUtils.find_repos(directory)
    for repo in repos:
        print(f"\nSyncing {repo}")
        kospex.sync_repo(repo)

@cli.command("developers")
@click.option('-repo', type=GitRepo(),
              help='Git repo directory to assess, confirm sync status')
@click.option('-days', type=int, default=90, help='Committed in the last X days.')
@click.option('-org_key', type=click.STRING, help='Format of SERVER~ORG')
@click.option('-repo_id', type=click.STRING)
@click.option('--all', is_flag=True, default=False, help="Find all developer history. ")
@click.option('-out', type=click.Path(), help='filename to write CSV results to.')
# pylint: disable=unused-argument
def devs(repo, days, repo_id, org_key, out, all):
    """ Information Stats about developers."""
    params = locals()
    if all:
        click.echo('Finding all developer history')
    else:
        click.echo(f'Searching for active developers (last {days} days)')
    kospex.active_developers(**params)

@cli.command("list-repos")
@click.argument('directory', type=click.Path(exists=True))
def find_repos(directory):
    """List all git repositories found in the given directory."""
    print("\nDirectory: " + os.path.abspath(directory))
    kospex.list_repos(directory)

@cli.command("tech-landscape")
@click.option('-repo', type=GitRepo())
@click.option('-repo_id', type=click.STRING)
@click.option("-metadata", is_flag=True, default=False,
              help="Use file metadata, NOT Git committed filenames.")
# pylint: disable=unused-argument
def tech_landscape(repo, repo_id, metadata):
    """Show the tech landscape (file extensions or metadata)."""
    kwargs = locals()
    kospex.tech_landscape(**kwargs)

@cli.command("sync-metadata")
@click.option('-repo', type=GitRepo())
@click.option('-directory', type=click.Path(exists=True))
def sync_metadata(repo,directory):
    """Sync file metadata for either a 'repo' or 'directory' of repos. """
    #print(f"Finding repos in {directory}")
    if directory and repo:
        print("Please specify either a -repo or a -directory, not both.")
    elif directory:
        kospex.sync_metadata(directory)
    elif repo:
        kospex.file_metadata(repo)
    else:
        print("Please specify either a '-repo' or a '-directory'.")

@cli.command("hotspot")
@click.option('-repo', type=GitRepo())
@click.option('-repo_id', type=click.Path())
@click.option("-by_file", is_flag=True, default=False, help="Calculate hotspot per file.")
# pylint: disable=unused-argument
def hotspot(repo, repo_id, by_file):
    """Find hotspots in the given repo."""
    params = locals()
    print("WARNING: EXPERIMENTAL")
    if repo or repo_id:
        kospex.hotspot(**params)
    else:
        print("Please specify either a '-repo' or a '-repo_id'.")

@cli.command("health-check")
@click.argument('directory', required=False, type=click.Path(exists=True))
def health_check(directory):
    """ Run a health check on a git repository."""

    warning_message = "\nWARNING: This is an experimental WIP feature."
    print(warning_message)
    print()
    if not directory:
        #directory = os.getcwd()
        directory = "."
        print("No directory specified, using current directory.")

    if not KospexUtils.is_git(directory):
        print("Directory is not a git repository.")
        exit(1)

    details = KospexUtils.get_git_stats(directory)

    print("\nDirectory: " + os.path.abspath(directory))
    # Get the # of authors
    # Get the active authors
    # Get the number of depencencies files
    kquery = KospexQuery()
    kdeps = KospexDependencies(kospex_db=kospex.kospex_db, kospex_query=kquery)
    results = kdeps.find_dependency_files(directory)
    records = KospexUtils.get_all_last_commit_info(results)
    stats = KospexUtils.repo_stats(records,"author_date")
    print(stats)

    details['dependency_files'] = len(results)
    print(f"Found {len(results)} dependency files.")
    active_dep_files = stats.get("Active",0)
    if active_dep_files > 0:
        active_dep_files_percent = (active_dep_files / len(results)) * 100
        details['active_dependency_files'] = f"{active_dep_files_percent:.2f}%"
    else:
        details['active_dependency_files'] = "0%"

    # Get the number of total dependencies
    # Get the status label
    print(f"{warning_message}\n")
    print(KospexUtils.get_keyvalue_table(details))


@cli.command("deps")
@click.option('-repo', type=GitRepo(), help="File path to git repo.")
@click.option('-file', type=click.Path(exists=True), help="Package file to assess.")
@click.option('-directory', type=click.Path(), help="Directory to search for dependency files.")
@click.option('-dev', is_flag=True, default=False, help="Include dev/test dependencies. EXPERIMENTAL.")
@click.option('-out', type=click.STRING, help="filename to write CSV results to.")
def deps(repo, file, directory, out, dev):
    """Find dependency files or assess a specific file."""
    kquery = KospexQuery()
    kdeps = KospexDependencies(kospex_db=kospex.kospex_db, kospex_query=kquery)

    if directory:

        results = kdeps.find_dependency_files(directory)
        records = []

        if results:

            #for file_path in results:
            #    commit_info = KospexUtils.get_last_commit_info(file_path)
            #    if commit_info:
            #        records.append(commit_info)

            records = KospexUtils.get_all_last_commit_info(results)

            if records:
                table = KospexUtils.get_dependency_files_table(records)
                print(table)

            if out:
                KospexUtils.list_dict_2_csv(records,out)

            stats = KospexUtils.repo_stats(records,"author_date")
            print("\nSummary of dependency files found in the directory:")
            print(stats)
            print()

        else:
            print("No package/dependency manager files found.")

    elif repo:
        #os.chdir(repo)
        #results = kdeps.find_dependency_files(".")
        results = kdeps.find_dependency_files(repo)
        # TODO - refactor, we no longer get the pkg_type
        if results:
            for file_path, pkg_type in results:
                print(f"File: {file_path} | Type: {pkg_type}")
        else:
            print("No package/dependency manager files found.")

    elif file:

        file_path = os.path.abspath(file)
        repo_info = kospex.file_repo_details(file)
        repo_authors = 0
        if repo_info:
            results = kquery.authors_by_repo(repo_info['_repo_id'])
            if results:
                repo_authors = len(results)

        params = {}
        params['dev_deps'] = dev
        params['repo_info'] = repo_info
        params['print_table'] = True
        params['results_file'] = out

        #records = kdeps.assess(file_path, results_file=out, repo_info=repo_info,
        #                       print_table=True)
        records = kdeps.assess(file_path, **params)
        # TODO - refactor this into a function
        total = len(records)
        count = 0
        author_count = 0
        repos_observerd = []
        for record in records:
            if 'versions_behind' in record and record['versions_behind'] > 2:
                count += 1
            if 'authors' in record and record['authors']:
                if not record.get('source_repo') in repos_observerd:
                    repos_observerd.append(record.get('source_repo'))
                    author_count += record['authors']

        if count and total:
            print(f"Total dependencies: {total} | Outdated(>2): {count}")
            print(f"Non Compliant: {count/total*100:.2f}%")
            print(f"Compliant: {(total-count)/total*100:.2f}%")
            print()
            print(f"# Dependency Authors: {author_count}")
            if repo_authors:
                print(f"# Repo Authors: {repo_authors}")
            if author_count and repo_authors:
                print(f"Dependency:Repo Author Ratio: {(repo_authors/author_count)*100:.5f}%")
        else:
            print("No dependencies found.")

        print()

    else:
        print("Please specify either a '-repo', '-directory' or a '-file'.")

@cli.command("author-tech")
@click.option('-author_email', type=click.STRING)
@click.option('-repo_id', type=click.STRING)
# pylint: disable=unused-argument
def author_tech(author_email,repo_id):
    """Show the tech landscape for a given author."""
    kwargs = locals()
    print(kwargs)
    results = kospex.kospex_query.author_tech(**kwargs)
    table = kospex.author_tech_pretty_table(results)
    print(table)

@cli.command("key-person")
@click.option('-top', type=int, default=4, help='The number of top authors to assess.')
@click.argument('directory',  type=GitRepo())
def key_person(directory,top):
    """ Identify the key person for a repo."""
    kgit = KospexGit()
    kgit.set_repo(directory)
    kquery = KospexQuery()

    table = KospexUtils.key_person_prettytable()
    headers = table.field_names

    active = kquery.commit_stats(repo_id=kgit.get_repo_id(),days=90)
    active_dict = {d["author"]: d for d in active}
    key = "commits"
    total_active_commits = sum(item[key] for item in active if key in item)

    authors = kquery.commit_stats(repo_id=kgit.get_repo_id())
    key = "commits"
    total_commits = sum(item[key] for item in authors if key in item)
    print(f"total commits: {total_commits}")
    for a in authors:
        a['active_commits'] = active_dict.get(a['author'],{}).get('commits',0)
        a['% commits'] = f"{a['commits'] / total_commits * 100:.1f}%"
        # TODO - We only want to do this if we're printing the table, modify if we're dumping to CSV
        a['last_commit'] = KospexUtils.extract_db_date(a['last_commit'])
        a['first_commit'] = KospexUtils.extract_db_date(a['first_commit'])

        if total_active_commits > 0:
            a['% active'] = f"{a['active_commits'] / total_active_commits * 100:.1f}%"
        else:
            a['% active'] = "0%"

    authors_dict = {d["author"]: d for d in authors}

    for a in authors[:top]:
        #a['active_commits'] = active_dict.get(a['author'],{}).get('commits',0)
        table.add_row(KospexUtils.get_values_by_keys(a, headers))

    top_authors_dict = {d["author"]: d for d in authors[:top]}

    for a in active[:top]:
        a_dict = top_authors_dict.get(a['author'])
        if not a_dict:
            a_dict = authors_dict[a['author']]
            table.add_row(KospexUtils.get_values_by_keys(a_dict, headers))

    print()
    print(table)
    print()

@cli.command("orgs")
def orgs():
    """List all the organizations in the database."""
    kquery = KospexQuery()
    orgs_list = kquery.orgs()
    table = KospexUtils.orgs_prettytable()
    for o in orgs_list:
        table.add_row(KospexUtils.get_values_by_keys(o, table.field_names))
    print(table)

@cli.command("sync-dependencies")
@click.option('-file', type=click.Path(exists=True), help="The dependency file to sync.")
@click.option('-repo', type=GitRepo())
@click.option('--dev', is_flag=True, default=False, help="Include dev/test dependencies. EXPERIMENTAL.")
def sync_dependencies(repo,file,dev):
    """ Clone and sync the dependencies for a repo/dependency file."""
    kquery = KospexQuery()
    kdeps = KospexDependencies(kospex_db=kospex.kospex_db, kospex_query=kquery)

    if file or repo:
        # We need one of these
        if file:
            file_path = os.path.abspath(file)
            print(f"Syncing dependencies for file: {file}")
            repo_info = kospex.file_repo_details(file)
            records = kdeps.assess(file_path, repo_info=repo_info,
                                   print_table=True,dev_deps=dev)

            for rec in records:

                if rec.get("source_repo"):
                    print(f'About to clone and sync {rec["source_repo"]}')
                    repo_path = kospex.git.clone_repo(rec["source_repo"])
                    if repo_path:
                        kospex.sync_repo(repo_path)
                    else:
                        print("No source repo URL for this dependency.")
                else:
                    print(f"No source repo URL for this dependency {rec.get('package_name')}")

        if repo:
            print(f"Syncing dependencies for repo: {repo}")
            print("NOT IMPLEMENTED!")

    else:
        print("Please specify either a '-repo' or a '-file'.")


@cli.command("know")
@click.argument('email',  type=click.STRING)
def knol(email):
    """Show the tech landscape for a given author."""

    print("WARNING: This is a work in progress.")

    nowish = datetime.now().isoformat()
    print(nowish)
    last30 = KospexUtils.date_days_ago(nowish, 60)

    kquery = KospexQuery()

    kd = kquery.tech_commits(author_email=email)
    kd.where("commits.committer_when", ">=", last30)

    print(kd.generate_sql(line=True))
    print(kd.get_bind_parameters())

    ar1 = {}
    ar2 = {}

    results = kospex.kospex_db.execute(kd.generate_sql(), kd.get_bind_parameters())
    for result in results:
        ar1[result[0]] = result[1]
        #print(result[0])
        print(result)

    print(ar1)

    kd2 = kquery.tech_commits(author_email=email)
    kd2.where("commits.committer_when", "<", last30)
    kd2_from = KospexUtils.date_days_ago(last30, 90)
    kd2.where("commits.committer_when", ">=", kd2_from)

    print("###")
    print(kd2.generate_sql(line=True))
    print(kd2.get_bind_parameters())

    results = kospex.kospex_db.execute(kd2.generate_sql(), kd2.get_bind_parameters())
    for result in results:
        ar2[result[0]] = result[1]
        print(result)

    ext_dif = KospexUtils.merge_dicts(ar1, ar2)
    print(ext_dif)

if __name__ == '__main__':
    cli()
